services:
  dragonify:
    container_name: dragonify
    image: ghcr.io/casse-boubou/dragonify:v1.0.0@sha256:c176e79e3e8c0823af86383fd9e4303846374c51a4cbcfa07863ec605b83ccee
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      - TZ=Etc/UTC
      - LOG_LEVEL=info
      - CONNECT_ALL=false
      - CUSTOMS_NETWORKS=ix-dragonify_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro