services:
  dragonify:
    container_name: dragonify
    image: ghcr.io/casse-boubou/dragonify:v1.1.1@sha256:4ef1ef470311a3e08f261c91480fdc362d20d6708783bff23ada195d661cc2c7
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      - TZ=Etc/UTC
      - LOG_LEVEL=info
      - CONNECT_ALL=false
      - CUSTOMS_NETWORKS=ix-dragonify_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro